export const TOGGLE_FAVS = "TOGGLE_FAVS";
export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const CHANGE_VALUE = "CHANGE_VALUE";
export const INPUT_CHANGE = "INPUT_CHANGE";